# Generated by Django 3.0.2 on 2020-01-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
